### PR TITLE
indigo changes

### PR DESCRIPTION
**Pull request by talregev**
Take @dougvk  changes from:
https://github.com/dougvk/tum_simulator
Also add my: @talregev change from:
https://github.com/talregev/tum_simulator

### CODE REVIEW

**Comment by talregev** [comment]
@dougvk check it out.
you can leave your opinion too.

**Comment by dougvk** [comment]
looks good to me! thanks for merging in :)

**Comment by talregev** [comment]
no problem. we using your repository for some time.
I hope it get accepted :)

**Comment by talregev** [comment]
I close this one. I open with full credit :)

**Pull request closed without merging**
