### PR TITLE
Port simulator to Indigo

### PR DESCRIPTION
**Pull request by garyservin**
Ported the simulator to work on indigo with gazebo 2.2.

This may be better located on a different "indigo" branch.

### CODE REVIEW

**Comment by dougvk** [comment]
this worked! thanks @garyservin

**Comment by przemb** [comment]
Hi,
I found one problem using this ported version. 
Almost everything works perfectly, but something is wrong with bottom camera. 
This camera don't display what is below the quadrotor, it displays what is above! 

 Please check this screen: http://snag.gy/L5Riw.jpg

This is a world from Gazebo and two windows from rviz. Left image is a view from bottom camera :( and right image is a view from front camera. Black shape near window of the house is quadrotors' model.

more info: http://answers.ros.org/question/196959/bottom-camera-problem/
and: http://answers.gazebosim.org/question/7391/problem-with-bottom-camera-and-sdf/
Please help. 

EDIT:

there is a small mistake, 

41 line in  cvg_sim_gazebo/urdf/quadrotor_sensors.urdf.xacro 
origin xyz="0.15 0.0 0.0" rpy="0 -${M_PI/2} 0"/ 
minus sign ' - ' next to $ is unwanted.

**Comment by garyservin** [comment]
@green96 I've also found that issue (we weren't using the bottom camera so we didn't see this issue before). Pushing changes now. Thanks for testing and reporting!

**Comment by johnGordon** [comment]
Hello, 
I am following installation instructions and when I do catkin_make I receive 

Building ARDroneTool/Lib
Building ARDroneTool/Lib
[  5%] Performing install step for 'ardronelib'
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[  5%] Completed 'ardronelib'
[  7%] Built target ardronelib
make: **\* [all] Error 2
Invoking "make -j4 -l4" failed

when launching the world, rostopic list only show me camera topics and not topics like ar_drone/land ,ar_drone/takeoff, cmd_vel and so...

thanks for your help

**Pull request closed without merging**
